/** A top-level section from llms-full.txt, delimited by ## Name {#anchor} */
export interface Section {
  /** Display name, e.g. "Single Sign-On" */
  name: string;
  /** Anchor slug, e.g. "sso" */
  anchor: string;
  /** Full markdown content between this header and the next */
  content: string;
  sizeBytes: number;
  lineCount: number;
  subsections: Subsection[];
}

/** A subsection within a top-level section, delimited by ### Heading */
export interface Subsection {
  title: string;
  /** Heading level (2 or 3) */
  level: number;
  content: string;
  sizeBytes: number;
}

/** Specification for a skill to be generated */
export interface SkillSpec {
  /** Skill directory name, e.g. "workos-sso" */
  name: string;
  /** Action-oriented 1-liner for frontmatter */
  description: string;
  /** Display title, e.g. "WorkOS Single Sign-On" */
  title: string;
  /** Source section anchor */
  anchor: string;
  /** Raw section content (context for generation) */
  content: string;
  /** Doc page URLs from llms.txt for runtime WebFetch */
  docUrls: string[];
  /** true = generated by script, false = hand-crafted */
  generated: boolean;
}

/** A generated skill ready to write to disk */
export interface GeneratedSkill {
  name: string;
  /** Relative path, e.g. "skills/workos-sso.md" or "skills/workos/SKILL.md" */
  path: string;
  content: string;
  sizeBytes: number;
  generated: boolean;
  /** SHA-256 hash of source doc content (for content-addressed locking) */
  sourceHash?: string;
}

// --- Split strategies ---

export type SplitStrategy =
  | { strategy: "single" }
  | { strategy: "per-subsection"; groupChildren?: boolean }
  | { strategy: "per-feature"; features: string[] }
  | { strategy: "per-api-domain" }
  | { strategy: "skip" };

export interface SectionConfig {
  split: SplitStrategy;
  /** If true, don't generate a skill for this section */
  skip?: boolean;
}

// --- Fetcher ---

export interface FetchResult {
  content: string;
  source: "cache" | "network";
  fetchedAt: Date;
}

export interface FetchOptions {
  /** Cache directory path. Default: .cache/ */
  cacheDir?: string;
  /** Cache TTL in ms. Default: 1 hour */
  maxAge?: number;
  /** Max retry attempts. Default: 3 */
  retries?: number;
}

// --- Domain Rules ---

export interface SkillRule {
  id: string;
  description: string;
  severity: "warn" | "error";
  promoted: boolean;
  must_contain?: Array<{ pattern: string; context: string }>;
  must_not_contain?: Array<{ pattern: string; context: string }>;
}

export interface RuleViolation {
  ruleId: string;
  description: string;
  severity: "warn" | "error";
  type: "missing" | "forbidden";
  pattern: string;
  context: string;
}

// --- Validator ---

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
  sectionCount: number;
  totalSize: number;
}
